apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
      version: green
  template:
    metadata:
      labels:
        app: flask
        version: blue
    spec:
      containers:
        - name: flask
          image: nginx
          ports:
            - containerPort: 5000
         
