apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
      version: blue
  template:
    metadata:
      labels:
        app: python-app
        version: blue
    spec:
      containers:
      - name: python-app
        image: rajukolupula/python-repo:latest
        ports:
        - containerPort: 5000
