apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
      version: green
  template:
    metadata:
      labels:
        app: python-app
        version: green
    spec:
      containers:
      - name: python-app
        image: rajukolupula/python-repo:newversion
        ports:
        - containerPort: 5000
