apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability

data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      googlecloud:
        project: project-8bfb738f-64f4-4a50-807

      debug: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [googlecloud, debug]
